### PR TITLE
Adding tests for hub_utils generator classes

### PR DESCRIPTION
**Pull request by punitkoura**
**Patch Description**
Adding tests for the generator classes in hub_utils.py
We basically present the same prompt to both GeneratorHubUtils and GeneratorUtils, and assert that the output is the same from both (albeit in different formats). This test shows parity between GeneratorHubUtils and GeneratorUtils.

**Testing steps**
Added tests

### CODE REVIEW

File: metaseq/distributed/fully_sharded_data_parallel.py [hunk 1]
```diff
@@ -104,6 +104,7 @@ def fsdp_enable_wrap(
         compute_dtype = torch.float32
     fsdp_config = {
         "process_group": group,
+        "process_group_reduce_scatter": group,
```
Comment (punitkoura) [inline metaseq/distributed/fully_sharded_data_parallel.py:107]: Rather than depend on the default value defined by fairscale, here we are ensuring process_group_reduce_scatter group is the same as the overall process group.

Comment (punitkoura) [reply metaseq/distributed/fully_sharded_data_parallel.py:107]: Depending on the default value sometimes leads to unpredictable behaviour, where the world size of the process group and the reduce scatter process group differ.

Comment (punitkoura) [reply metaseq/distributed/fully_sharded_data_parallel.py:107]: https://github.com/facebookresearch/fairscale/blob/main/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L361

File: gpu_tests/test_hub_utils.py [hunk 2]
```diff
@@ -0,0 +1,233 @@
...
+        overall_generation = distributed_utils.call_main(
+            cfg, generate_using_generator_interface
+        )
+        # We can potentially pass a list of inputs to the generate function.
+        # Here, we look at the first (and only) generation
+        [generation_for_prompt] = overall_generation
+        # We use best_of = 1, so we get only one beam search result
+        [generated_beam] = generation_for_prompt
+
+        EXPECTED_OUTPUT = {
```
Comment (stephenroller) [inline gpu_tests/test_hub_utils.py:162]: Should we consider using a regression testing framework to facilitate updating the expected output in the future?

https://pypi.org/project/pytest-regressions/

File: metaseq/distributed/fully_sharded_data_parallel.py (hunk 1 above)
Comment (stephenroller) [reply metaseq/distributed/fully_sharded_data_parallel.py:107]: Hm, our branch of fairscale supposedly fixed this already... But maybe it's better to handle it here for us.

File: gpu_tests/test_hub_utils.py [hunk 3]
```diff
@@ -0,0 +1,233 @@
...
+            np.allclose(
+                TOKEN_SCORES[1:], generated_beam["positional_scores"].cpu(), atol=1e-2
+            )
+        )
+        self.assertTrue(np.isclose(-3.4824, generated_beam["score"].item(), atol=1e-2))
+
+    def tearDown(self):
+        # Tear down model parallel
+        destroy_model_parallel()
+        distributed_utils._USE_MEGATRON = False
```
Comment (stephenroller) [inline gpu_tests/test_hub_utils.py:229]: we should maybe switch to always using megatron... something for the backlog

File: metaseq/hub_utils.py [hunk 4]
```diff
@@ -435,38 +435,6 @@ def _build_batches(
         return batch_iterator
 
 
-class BPEHubInterface(object):
```
Comment (stephenroller) [inline metaseq/hub_utils.py:438]: Should we keep these tests until we remove the items they're testing?

Comment (punitkoura) [reply metaseq/hub_utils.py:438]: Reverted the deletion

File: gpu_tests/test_hub_utils.py (hunk 2 above)
Comment (punitkoura) [reply gpu_tests/test_hub_utils.py:162]: Good point! Looking into this

Comment (punitkoura) [reply gpu_tests/test_hub_utils.py]: @stephenroller  Made this change

**Comment by punitkoura** [comment]
Made all the requested change. The PR is again ready for review

**Comment by lilisierrayu** [comment]
can you be more specific, what is covered in this test?

**Comment by punitkoura** [comment]
> can you be more specific, what is covered in this test?

Sorry, added more details to the blurb.

>We basically present the same prompt to both GeneratorHubUtils and GeneratorUtils, and assert that the output is the same from both (albeit in different formats). This test shows parity between GeneratorHubUtils and GeneratorUtils.

File: gpu_tests/test_hub_utils.py [hunk 5]
```diff
@@ -0,0 +1,187 @@
...
+    # fsdp_wrap will be a no-op if not using FSDP
+    if hasattr(model, "make_generation_fast_"):
+        model.make_generation_fast_()
+    return fsdp_wrap(model)
+
+
+def override_task(model):
+    # HACK: Use special version of the language_modeling task for inference with the models
+    # trained with streaming_language_modeling.
+    # TODO: More elegant solution would be to decouple the training and inference logic for the tasks
```
Comment (lilisierrayu) [inline gpu_tests/test_hub_utils.py:34]: I think we should be able to "language_modeling_inference_for_models_trained_with_streaming', the API only needs "language_modeling" to run.

**Review by stephenroller — COMMENTED** [review]
:-X are the binary files needed? Can we just serialize them to lists so they go into the yml file?

**Comment by punitkoura** [comment]
> :-X are the binary files needed? Can we just serialize them to lists so they go into the yml file?

Looks like it is required :( .
If I save it as an XML, the framework does exact matching which won't work for us because of GPU differences etc.

**Comment by punitkoura** [comment]
I guess we could make changes to the code to save the file in cleartext https://github.com/ESSS/pytest-regressions/blob/master/src/pytest_regressions/ndarrays_regression.py#L270

File: gpu_tests/test_hub_utils.py [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+    # https://github.com/pytorch/pytorch/issues/48203
+    dist.destroy_process_group()
+    return generated_text
+
+
+def generate_using_generator_hub_interface(cfg: MetaseqConfig, **kwargs):
+    model_path = os.path.join(os.path.dirname(__file__), "125m")
+    kwargs = {
+        "suffix": f"-model_part-{torch.distributed.get_rank()}",
+        "criterion": "cross_entropy",
```
Comment (lilisierrayu) [inline gpu_tests/test_hub_utils.py:84]: do we need this?

File: gpu_tests/test_hub_utils.py [hunk 7]
```diff
@@ -0,0 +1,187 @@
...
+        "bpe": "hf_byte_bpe",
+        "post_build_model_hook": default_post_build_model_hook,
+        "bpe_merges": os.path.join(kwargs["model_path"], "gpt2-merges.txt"),
+        "merges_filename": os.path.join(kwargs["model_path"], "gpt2-merges.txt"),
+        "bpe_vocab": os.path.join(kwargs["model_path"], "gpt2-vocab.json"),
+        "vocab_filename": os.path.join(kwargs["model_path"], "gpt2-vocab.json"),
+        "bpe_add_prefix_space": False,
+        "specify_arch": True,
```
Comment (lilisierrayu) [inline gpu_tests/test_hub_utils.py:92]: do we need "specify_arch"?

File: gpu_tests/test_hub_utils.py [hunk 8]
```diff
@@ -0,0 +1,187 @@
...
+    # We can potentially pass a list of inputs to the generate function.
+    # Here, we look at the first (and only) generation
+    [generation_for_prompt] = overall_generation
+    # We use best_of = 1, so we get only one beam search result
+    [generated_beam] = generation_for_prompt
+
+    ndarray_data = {
+        key: value.cpu()
+        for key, value in generated_beam.items()
+        if key in ["tokens", "score", "positional_scores"]
```
Comment (lilisierrayu) [inline gpu_tests/test_hub_utils.py:179]: The tokens here I believe are the indexes, can we also test the decoded string, as decode is part of generator_hub_interface.

File: gpu_tests/test_hub_utils.py [hunk 9]
```diff
@@ -0,0 +1,187 @@
...
+from metaseq.dataclass.configs import MetaseqConfig
+import numpy as np
+from megatron.mpu import destroy_model_parallel
+from metaseq.distributed import fsdp_wrap, fsdp_enable_wrap
+from metaseq import hub_utils
+import torch.distributed as dist
+import torch
+
+
+PROMPT = [133, 313, 1224, 15, 5, 856, 17527, 594, 98, 5, 11471, 3820, 19, 514, 4]
```
Comment (lilisierrayu) [inline gpu_tests/test_hub_utils.py:19]: T

**Review by suchenzang — APPROVED** [review]

**Comment by suchenzang** [comment]
Tracking all of the above requests in https://github.com/facebookresearch/metaseq/issues/371

Merging this PR now since it seems to fix our failing GPU test in main 😅

**Comment by roywei** [comment]
Hi, i'm getting `got an unexpected keyword argument 'process_group_reduce_scatter'` error after this PR. Reverting this commit works. Any idea? should I use another version of fairscale?
```
Traceback (most recent call last):
  File "./slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq_cli/train.py", line 624, in <module>
    cli_main()
  File "./slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq_cli/train.py", line 620, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/distributed/utils.py", line 274, in call_main
    return distributed_main(
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/distributed/utils.py", line 212, in distributed_main
    retval = main(cfg, **kwargs)
  File "./slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq_cli/train.py", line 110, in main
    task.build_model(cfg.model),
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/tasks/base_task.py", line 321, in build_model
    model = models.build_model(cfg, self)
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/models/__init__.py", line 87, in build_model
    return model.build_model(cfg, task)
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/model_parallel/models/transformer_lm.py", line 55, in build_model
    decoder = ModelParallelTransformerDecoder(
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/models/transformer_decoder.py", line 129, in __init__
    layers.append(self.build_decoder_layer(args))
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/models/transformer_decoder.py", line 278, in build_decoder_layer
    layer = fsdp_wrap(
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/distributed/fully_sharded_data_parallel.py", line 148, in fsdp_wrap
    return wrap(module, **kwargs)
  File "/fsx/opt_deps/fairscale/fairscale/nn/wrap/auto_wrap.py", line 170, in wrap
    return ConfigAutoWrap.wrapper_cls(module, **wrap_overrides)
  File "/fsx/opt_deps/metaseq/slurm_snapshot_code_oss/2022-10-06T07_36_25.599262/metaseq/distributed/fully_sharded_data_parallel.py", line 50, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'process_group_reduce_scatter'
```

**Comment by suchenzang** [comment]
@stephenroller we haven't updated the setup instructions yet
